name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t imranf620/vite-app .
          docker push imranf620/vite-app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # SSH to EC2 and pull the Docker image
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull imranf620/vite-app:latest
            docker stop vite-app || true
            docker rm vite-app || true
            docker run -d --name vite-app -p 80:80 imranf620/vite-app:latest
