name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to DockerHub using GitHub secrets for security
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image and push it to DockerHub
      - name: Build and push Docker image
        run: |
          docker build -t imranf620/vite-app .
          docker push imranf620/vite-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # SSH into EC2, pull the new Docker image, and deploy it
      - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.8 
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 public IP or DNS
          username: ${{ secrets.EC2_USER }}  # EC2 user (e.g., ec2-user, ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}  # The private SSH key from GitHub Secrets
          script: |
            # Pull the latest Docker image from DockerHub
            docker pull imranf620/vite-app:latest

            # Stop and remove any running containers with the same name
            docker stop vite-app || true
            docker rm vite-app || true

            # Run the new Docker container in detached mode
            docker run -d --name vite-app -p 80:80 imranf620/vite-app:latest
